#!/usr/bin/env python3
"""discover/ 共享配置 — 路径、分类体系、质量等级"""

from pathlib import Path

# ──────────────────────────────────────────────
# 路径
# ──────────────────────────────────────────────
SCRIPT_DIR = Path(__file__).parent.resolve()
PROJECT_ROOT = SCRIPT_DIR.parent.parent
IMPORT_DIR = PROJECT_ROOT / "import"
DISCOVER_DIR = PROJECT_ROOT / "discover"
KNOWLEDGE_DIR = PROJECT_ROOT / "knowledge"

# discover 子目录
DISCOVER_QUESTIONS = DISCOVER_DIR / "questions"
DISCOVER_NEWWIKI2 = DISCOVER_DIR / "newwiki2"
DISCOVER_NEWWIKI2_DOCS = DISCOVER_NEWWIKI2 / "docs"
DISCOVER_NEWWIKI2_RENAME_TOOLS = DISCOVER_NEWWIKI2 / "rename_tools"
DISCOVER_SITE = DISCOVER_DIR / "site"
DISCOVER_NEWWIKI = DISCOVER_DIR / "newwiki"
DISCOVER_ROOT = DISCOVER_DIR / "root"

# 导入来源映射
IMPORT_SOURCES = {
    "doubao": IMPORT_DIR / "doubao",
    "cnblogs": IMPORT_DIR / "cnblogs",
    "md": IMPORT_DIR / "md",
    "千问": IMPORT_DIR / "千问",
    "work": IMPORT_DIR / "work",
    "fetched": IMPORT_DIR / "fetched",
}

# ──────────────────────────────────────────────
# 分类体系（继承自 scripts/tools/classify-questions.py）
# ──────────────────────────────────────────────
CLASSIFICATION_SYSTEM = {
    "硬件架构": {
        "keywords": ["服务器", "GPU", "CPU", "PCIe", "NVLink", "主板", "机箱", "机柜",
                      "散热", "液冷", "风冷", "供电", "电源", "拓扑", "互联"],
        "description": "服务器/GPU 硬件架构、互连、供电散热",
        "knowledge_target": "knowledge/02_rd/",
    },
    "AI 技术": {
        "keywords": ["大模型", "LLM", "训练", "推理", "MoE", "Transformer", "Agent",
                     "RAG", "微调", "蒸馏", "量化", "NCCL", "RDMA"],
        "description": "AI 大模型、训练推理、Agent 框架",
        "knowledge_target": "knowledge/03_AI/",
    },
    "系统软件": {
        "keywords": ["BMC", "BIOS", "固件", "firmware", "驱动", "driver", "OS",
                     "Linux", "内核", "Redfish", "IPMI", "UEFI"],
        "description": "固件、操作系统、系统管理软件",
        "knowledge_target": "knowledge/02_rd/05_software/",
    },
    "数据中心": {
        "keywords": ["数据中心", "data center", "POD", "集群", "网络", "交换机",
                     "800VDC", "HVDC", "液冷", "功耗", "能效", "绿电"],
        "description": "数据中心基础设施、供电散热、网络架构",
        "knowledge_target": "knowledge/01_survey/data-center/",
    },
    "存储": {
        "keywords": ["存储", "NVMe", "SSD", "CXL", "RAID", "分布式存储", "对象存储",
                     "文件系统", "数据保护", "灾备"],
        "description": "存储技术、协议、架构",
        "knowledge_target": "knowledge/01_survey/components-storage/",
    },
    "运维管理": {
        "keywords": ["运维", "监控", "部署", "K8s", "Kubernetes", "Docker", "CMDB",
                     "Zabbix", "Prometheus", "告警", "日志"],
        "description": "运维监控、容器编排、自动化部署",
        "knowledge_target": "knowledge/01_survey/ops-system/",
    },
    "方法论": {
        "keywords": ["架构", "设计", "方法论", "MECE", "第一性原理", "五看三定",
                     "流程", "规范", "标准", "最佳实践"],
        "description": "设计方法、分析框架、工程规范",
        "knowledge_target": "02_rd/00_shared/02_concepts/",
    },
    "行业": {
        "keywords": ["行业", "趋势", "市场", "投资", "财报", "竞争", "生态",
                     "WAIC", "GTC", "发布会", "战略"],
        "description": "行业动态、市场分析、竞品情报",
        "knowledge_target": "knowledge/01_survey/industry-research/",
    },
    "其他": {
        "keywords": [],
        "description": "未匹配分类的兜底",
        "knowledge_target": "knowledge/06_others/",
    },
}

# ──────────────────────────────────────────────
# 质量等级与检测规则
# ──────────────────────────────────────────────
QUALITY_LEVELS = {
    "⭐⭐⭐⭐": {"name": "验证通过", "min_score": 80, "action": "可迁移到 knowledge/"},
    "⭐⭐⭐":  {"name": "内容提升", "min_score": 60, "action": "可进入质量门禁"},
    "⭐⭐":   {"name": "AI 初提",  "min_score": 30, "action": "可进入增强管道"},
    "⭐":    {"name": "原始接入",  "min_score": 0,  "action": "排队等待处理"},
}

# 空洞检测关键词（匹配到表示内容可能质量问题）
HOLLOW_PATTERNS = [
    "非常重要", "值得关注", "具有重要意义", "不可或缺",
    "综上所述", "可想而知", "毫无疑问", "显而易见",
    "A方案/B方案/C方案", "方案一/方案二/方案三",
    "有待进一步研究", "需要继续探索",
]

# ──────────────────────────────────────────────
# 质量控制
# ──────────────────────────────────────────────
DEFAULT_BATCH_SIZE = 10
MAX_KEYWORDS = 15
MIN_KEYWORDS = 5
MAX_FILENAME_LEN = 120
SLUG_SEPARATOR = "-"

# ──────────────────────────────────────────────
# 文件名生成配置（继承自 rename_tools/dict.py）
# ──────────────────────────────────────────────
MAX_SHORT_FILENAME_LEN = 30
FILENAME_EXT = ".md"

CATEGORY_CODES = {
    "AI-Agent技术架构": "aag",
    "AI伦理与安全": "aes",
    "AI应用与落地实践": "aap",
    "AI编程与开发工具": "adt",
    "企业管理与运营": "emo",
    "其他_后端开发_backup": "obd",
    "其他_数学算法": "oma",
    "其他_数据科学": "ods",
    "其他_综合技术": "oct",
    "其他_编程语言": "opl",
    "大模型技术与原理": "lmf",
    "技术选型与方案对比": "tsc",
    "数据与存储技术": "dst",
    "数据中心与基础设施": "dci",
    "方法论与工具": "mwt",
    "服务器与硬件架构": "sha",
    "网络与系统运维": "nso",
    "行业趋势与洞察": "iti",
}

STOPWORDS = {
    "什么", "怎么", "如何", "为什么", "哪些", "哪种", "哪一种", "几个", "多少",
    "吗", "呢", "啊", "呀", "吧", "的", "了", "是", "在", "有", "和", "与", "及",
    "或者", "还是", "以及", "等", "等等", "比如", "例如", "如", "假设", "如果",
    "可以", "能够", "应该", "需要", "必须", "想要", "希望", "想", "要", "请",
    "帮", "帮我", "帮忙", "介绍", "介绍一下", "解释", "解释下", "解释一下",
    "详细", "详细描述", "详细说明", "详细解释", "详细介绍", "尽可能", "尽量",
    "下面", "以下", "上述", "上面", "其中", "另外", "此外", "同时", "并且",
    "进行", "做", "给出", "提供", "获取", "得到", "获得", "实现", "完成",
    "分别", "分别介绍", "具体", "具体说", "具体介绍", "简要", "简单",
    "分析", "总结", "汇总", "梳理", "梳理下", "概述", "概述下", "描述", "说明",
    "对比", "比较", "区别", "差异", "相同", "相似",
    "及", "或", "和", "与", "了", "的", "和", "等", "们",
    "我", "我们", "你", "您", "他", "她", "它", "他们", "她们", "它们",
    "公司", "企业", "组织", "团队", "项目", "产品", "系统",
    "一个", "一些", "这种", "那种", "这种", "此", "该", "这", "那",
    "今天", "明天", "昨天", "现在", "未来", "过去", "之前", "之后",
    "问题", "内容", "方式", "方法", "方面", "地方", "时候", "时间",
    "情况", "场景", "案例", "实例", "示例",
}

TERM_DICT = {
    "智能体": "agent", "代理": "agent", "大模型": "llm", "语言模型": "llm",
    "基础模型": "foundation_model", "通用模型": "general_model",
    "垂直模型": "vertical_model", "垂直场景": "vertical",
    "提示词": "prompt", "提示": "prompt", "提示工程": "prompt_eng",
    "提示注入": "prompt_inject", "越狱": "jailbreak",
    "嵌入": "embedding", "向量": "vector", "向量库": "vector_db",
    "向量数据库": "vector_db", "知识库": "kb", "知识图谱": "kg",
    "知识管理": "km", "知识": "knowledge", "检索": "retrieval",
    "召回": "recall", "重排": "rerank", "排序": "rank",
    "微调": "finetune", "预训练": "pretrain", "训练": "training",
    "推理": "inference", "对齐": "alignment", "安全对齐": "safety_align",
    "强化学习": "rl", "深度学习": "dl", "机器学习": "ml",
    "学习": "learning", "多模态": "multimodal", "视觉": "vision",
    "语言": "language", "文本": "text", "语音": "speech",
    "图像": "image", "视频": "video", "音频": "audio",
    "生成": "generation", "生成式": "generative", "扩散模型": "diffusion",
    "transformer": "transformer", "注意力": "attention", "编码器": "encoder",
    "解码器": "decoder", "编码": "encode", "解码": "decode",
    "压缩": "compress", "量化": "quantization", "蒸馏": "distill",
    "剪枝": "pruning", "参数": "param", "超参数": "hyperparam",
    "权重": "weight", "梯度": "gradient", "损失": "loss",
    "目标函数": "obj_func", "激活函数": "activation", "softmax": "softmax",
    "token": "token", "tokens": "tokens", "上下文": "context",
    "记忆": "memory", "反思": "reflection", "推理链": "reasoning_chain",
    "思维链": "cot", "工具调用": "tool_call", "工具": "tool",
    "工具箱": "toolkit", "插件": "plugin", "扩展": "extension",
    "技能": "skill", "工作流": "workflow", "编排": "orchestration",
    "协同": "collab", "协作": "collab", "多智能体": "multi_agent",
    "单体": "single", "数字员工": "digital_worker", "数字人": "digital_human",
    "智能": "smart", "智慧": "wisdom",
    "架构": "arch", "分层架构": "layered_arch", "微服务": "microservice",
    "单体应用": "monolith", "分布式": "distributed", "集中式": "centralized",
    "云原生": "cloud_native", "组件": "component", "模块": "module",
    "服务": "service", "服务化": "servitization", "接口": "interface",
    "协议": "protocol", "标准": "standard", "规范": "spec",
    "模式": "pattern", "设计模式": "design_pattern", "设计": "design",
    "原则": "principle", "方法论": "methodology", "方法": "method",
    "策略": "strategy", "机制": "mechanism", "方案": "solution",
    "选型": "selection", "对比": "compare", "比较": "compare",
    "区别": "diff", "差异": "diff", "优缺点": "pros_cons",
    "优点": "pros", "缺点": "cons", "优势": "advantage",
    "劣势": "disadvantage", "风险": "risk", "挑战": "challenge",
    "机遇": "opportunity", "趋势": "trend", "演进": "evolution",
    "发展": "development", "未来": "future", "前沿": "frontier",
    "创新": "innovation", "转型": "transformation", "升级": "upgrade",
    "迁移": "migration", "集成": "integration", "兼容": "compat",
    "适配": "adapt", "定制": "custom", "配置": "config",
    "部署": "deploy", "实施": "implement", "落地": "landing",
    "应用": "app", "应用场景": "use_case", "场景": "scene",
    "案例": "case", "实践": "practice", "最佳实践": "best_practice",
    "经验": "experience", "教训": "lesson", "总结": "summary",
    "复盘": "review", "评估": "evaluate", "衡量": "measure",
    "指标": "metric", "维度": "dimension", "要素": "factor",
    "特征": "feature", "标签": "label", "属性": "attribute",
    "能力": "capability", "功能": "function", "特性": "feature",
    "特性集": "features", "版本": "version", "迭代": "iteration",
    "发布": "release", "上线": "go_live", "下线": "offline",
    "灰度": "canary", "回滚": "rollback",
    "数据": "data", "数据库": "db", "关系数据库": "rdbms",
    "时序数据库": "tsdb", "图数据库": "graph_db", "键值": "kv",
    "键值数据库": "kv_db", "文档数据库": "doc_db", "列式": "columnar",
    "列存": "columnar", "行存": "row", "存储": "storage",
    "对象存储": "object_storage", "块存储": "block_storage",
    "文件存储": "file_storage", "文件系统": "fs",
    "分布式存储": "dist_storage", "缓存": "cache", "内存": "memory",
    "内存数据库": "imdb", "持久化": "persistence", "持久层": "persistence",
    "事务": "transaction", "acid": "acid", "base": "base",
    "cap": "cap", "一致性": "consistency", "可用性": "availability",
    "分区容错": "partition", "分区": "partition", "分片": "shard",
    "分库分表": "sharding", "主从": "master_slave", "副本": "replica",
    "复制": "replication", "同步": "sync", "异步": "async",
    "并发": "concurrency", "并行": "parallel", "锁": "lock",
    "互斥": "mutex", "信号量": "semaphore", "队列": "queue",
    "消息队列": "mq", "消息": "message", "通知": "notify",
    "事件": "event", "事件驱动": "event_driven", "流式": "streaming",
    "流处理": "stream", "批处理": "batch", "etl": "etl",
    "数据仓库": "dw", "数据湖": "data_lake", "数据治理": "data_gov",
    "数据资产": "data_asset", "数据质量": "data_quality", "元数据": "metadata",
    "主数据": "master_data", "数据建模": "data_modeling", "模型": "model",
    "建模": "modeling", "查询": "query", "索引": "index",
    "倒排索引": "inverted_index", "全文检索": "fulltext",
    "搜索引擎": "search_engine", "聚合": "aggregate", "统计": "stats",
    "分析": "analytics", "数据分析": "data_analysis", "bi": "bi",
    "报表": "report", "可视化": "viz", "dashboard": "dashboard",
    "监控": "monitor", "告警": "alert", "日志": "log",
    "链路": "trace", "追踪": "trace", "诊断": "diagnose",
    "排查": "troubleshoot",
    "服务器": "server", "硬件": "hardware", "软件": "software",
    "固件": "firmware", "bios": "bios", "bmc": "bmc", "ilo": "ilo",
    "ipmi": "ipmi", "redfish": "redfish", "cpu": "cpu", "gpu": "gpu",
    "npu": "npu", "tpu": "tpu", "fpga": "fpga", "asic": "asic",
    "加速卡": "accelerator", "显卡": "gpu", "内存": "dram", "硬盘": "disk",
    "ssd": "ssd", "nvme": "nvme", "光模块": "optical", "网卡": "nic",
    "交换机": "switch", "路由器": "router", "防火墙": "firewall",
    "负载均衡": "lb", "网关": "gateway", "代理": "proxy",
    "反向代理": "reverse_proxy", "cdn": "cdn", "dns": "dns",
    "ip": "ip", "tcp": "tcp", "udp": "udp", "http": "http",
    "https": "https", "tls": "tls", "ssl": "ssl", "证书": "cert",
    "加密": "encrypt", "解密": "decrypt", "签名": "sign", "验签": "verify",
    "哈希": "hash", "摘要": "digest", "对称加密": "symmetric",
    "非对称": "asymmetric", "rsa": "rsa", "aes": "aes",
    "sm2": "sm2", "sm3": "sm3", "sm4": "sm4", "国密": "china_crypto",
    "数据中心": "dc", "机房": "datacenter", "机架": "rack", "机柜": "cabinet",
    "ups": "ups", "电源": "power", "散热": "cooling", "制冷": "cooling",
    "空调": "hvac", "pue": "pue", "能效": "energy_eff", "能耗": "energy",
    "绿色": "green", "低碳": "low_carbon", "边缘计算": "edge",
    "云计算": "cloud", "私有云": "private_cloud", "公有云": "public_cloud",
    "混合云": "hybrid_cloud", "虚拟化": "virt", "容器": "container",
    "docker": "docker", "kubernetes": "k8s", "k8s": "k8s",
    "pod": "pod", "集群": "cluster", "节点": "node", "调度": "schedule",
    "编排": "orchestrate", "helm": "helm", "istio": "istio",
    "service_mesh": "mesh",
    "编程": "coding", "代码": "code", "源码": "source", "程序": "program",
    "函数": "function", "类": "class", "对象": "object", "方法": "method",
    "变量": "var", "常量": "const", "类型": "type", "接口": "api",
    "api": "api", "sdk": "sdk", "框架": "framework", "库": "lib",
    "依赖": "dep", "包": "pkg", "模块": "module", "依赖管理": "dep_mgmt",
    "版本管理": "version_ctrl", "git": "git", "github": "github",
    "gitlab": "gitlab", "代码审查": "code_review", "测试": "test",
    "单元测试": "unit_test", "集成测试": "integ_test", "压力测试": "stress_test",
    "性能测试": "perf_test", "自动化": "automation", "ci/cd": "cicd",
    "ci": "ci", "cd": "cd", "devops": "devops", "可观测": "observability",
    "调试": "debug", "异常": "exception", "错误": "error", "故障": "fault",
    "容错": "fault_tol", "高可用": "ha", "容灾": "dr", "备份": "backup",
    "恢复": "recovery", "灾备": "dr", "ras": "ras", "ece": "ece",
    "rma": "rma", "可用性": "availability", "可靠性": "reliability",
    "可维护性": "maintainability", "可扩展性": "scalability",
    "扩展性": "scalability", "弹性": "elasticity", "性能": "performance",
    "吞吐": "throughput", "吞吐量": "throughput", "qps": "qps",
    "tps": "tps", "延迟": "latency", "响应时间": "rt",
    "并发": "concurrency", "连接数": "connections", "带宽": "bandwidth",
    "iops": "iops", "时延": "latency", "抖动": "jitter",
    "瓶颈": "bottleneck", "优化": "optimize", "调优": "tuning",
    "压测": "bench",
    "企业": "enterprise", "公司": "company", "组织": "org", "团队": "team",
    "管理": "mgmt", "运营": "ops", "经营": "business", "战略": "strategy",
    "规划": "planning", "决策": "decision", "执行": "execution", "汇报": "report",
    "材料": "material", "演讲": "speech", "汇报材料": "report_mat",
    "汇报对象": "audience", "roi": "roi", "成本": "cost",
    "成本结构": "cost_struct", "收益": "revenue", "利润": "profit",
    "盈利": "profit", "亏损": "loss", "财务": "finance", "预算": "budget",
    "投资": "invest", "估值": "valuation", "市值": "mkt_cap",
    "股权": "equity", "股权结构": "equity_struct", "合规": "compliance",
    "治理": "governance", "审计": "audit", "风险": "risk",
    "内部控制": "internal_ctrl", "iso": "iso", "信息安全": "info_sec",
    "信息": "info", "安全": "security", "防护": "protection",
    "防御": "defense", "攻击": "attack", "漏洞": "vuln", "威胁": "threat",
    "渗透": "penetration", "扫描": "scan", "授权": "auth",
    "认证": "authn", "鉴权": "authz", "权限": "perm", "角色": "role",
    "用户": "user", "客户": "customer", "租户": "tenant", "员工": "employee",
    "人才": "talent", "招聘": "recruit", "培训": "training", "培养": "develop",
    "考核": "appraisal", "绩效": "performance", "激励": "incentive",
    "薪酬": "salary", "组织架构": "org_struct", "事业部": "bu",
    "部门": "dept", "岗位": "position", "职责": "responsibility",
    "权力": "power", "权利": "right", "义务": "obligation",
    "协同": "collab", "冲突": "conflict", "沟通": "communication",
    "倾听": "listen", "反馈": "feedback", "复盘": "review",
    "学习": "learning", "成长": "growth", "领导力": "leadership",
    "管理者": "manager", "领导": "leader", "决策质量": "decision_quality",
    "权力结构": "power_struct", "父子定律": "father_son", "vark": "vark",
    "ipd": "ipd", "crm": "crm", "erp": "erp", "mes": "mes",
    "plm": "plm", "scm": "scm", "wms": "wms", "bom": "bom",
    "sku": "sku", "供应链": "supply_chain",
    "算法": "algo", "数据结构": "ds", "复杂度": "complexity",
    "时间复杂度": "time_complexity", "空间复杂度": "space_complexity",
    "图论": "graph_theory", "树": "tree", "二叉树": "binary_tree",
    "图": "graph", "链表": "linked_list", "栈": "stack", "队列": "queue",
    "堆": "heap", "哈希表": "hash_table", "排序算法": "sort_algo",
    "查找": "search", "动态规划": "dp", "贪心": "greedy", "回溯": "backtrack",
    "递归": "recursion", "迭代": "iteration", "分治": "divide_conquer",
    "分支限界": "branch_bound", "概率": "prob", "统计": "stats",
    "概率论": "prob_theory", "数理统计": "math_stats", "线性代数": "linalg",
    "矩阵": "matrix", "向量": "vector", "张量": "tensor", "微积分": "calculus",
    "优化算法": "opt_algo", "梯度下降": "gradient_descent", "牛顿法": "newton",
    "共轭梯度": "conjugate_grad", "遗传算法": "ga", "粒子群": "pso",
    "量子粒子群": "qpso", "蚁群": "aco", "模拟退火": "sa",
    "禁忌搜索": "tabu", "强化学习": "rl", "马尔可夫": "markov", "mdp": "mdp",
    "q学习": "q_learning", "策略梯度": "policy_grad", "actor": "actor",
    "critic": "critic", "ppo": "ppo", "dqn": "dqn", "sac": "sac",
    "ddpg": "ddpg", "td3": "td3", "蒙特卡洛": "monte_carlo",
    "贝叶斯": "bayes", "朴素贝叶斯": "naive_bayes", "决策树": "decision_tree",
    "随机森林": "random_forest", "svm": "svm", "knn": "knn", "kmeans": "kmeans",
    "聚类": "clustering", "分类": "classification", "回归": "regression",
    "线性回归": "linear_reg", "逻辑回归": "logistic_reg", "主成分": "pca",
    "降维": "dim_reduce", "特征工程": "feat_eng", "特征选择": "feat_select",
    "特征提取": "feat_extract", "交叉验证": "cv", "过拟合": "overfit",
    "欠拟合": "underfit", "正则化": "regularization", "损失函数": "loss",
    "激活函数": "activation", "卷积": "conv", "cnn": "cnn", "rnn": "rnn",
    "lstm": "lstm", "gru": "gru", "注意力": "attention", "bert": "bert",
    "gpt": "gpt", "llama": "llama", "claude": "claude", "gemini": "gemini",
    "通义": "qwen", "千问": "qwen", "文心": "ernie", "glm": "glm",
    "chatgpt": "chatgpt", "rag": "rag", "agent": "agent", "mcp": "mcp",
    "langchain": "langchain", "langgraph": "langgraph", "autogen": "autogen",
    "crewai": "crewai", "dify": "dify", "coze": "coze", "fastgpt": "fastgpt",
    "openai": "openai", "anthropic": "anthropic", "huggingface": "huggingface",
    "ollama": "ollama", "vllm": "vllm", "tensorrt": "tensorrt", "onnx": "onnx",
    "pytorch": "pytorch", "tensorflow": "tensorflow", "cuda": "cuda",
    "nccl": "nccl", "mpi": "mpi", "rdma": "rdma", "infiniband": "ib",
    "roce": "roce", "nvlink": "nvlink", "pcie": "pcie", "cxl": "cxl",
    "ddr": "ddr", "hbm": "hbm", "hdi": "hdi", "pcb": "pcb",
    "主板": "motherboard", "bios": "bios", "uefi": "uefi", "ras": "ras",
    "思维模型": "mental_model", "思维": "thinking", "逻辑": "logic",
    "逻辑漏洞": "logic_flaw", "逻辑谬误": "fallacy", "逻辑链": "logic_chain",
    "结构化": "structured", "结构化思维": "structured_thinking", "mece": "mece",
    "第一性原理": "first_principle", "抽象": "abstraction", "分层": "layered",
    "分治": "divide", "演化": "evolution", "类比": "analogy", "隐喻": "metaphor",
    "修辞": "rhetoric", "论证": "argument", "推理": "reasoning",
    "演绎": "deduction", "归纳": "induction", "溯因": "abduction",
    "证伪": "falsify", "可证伪": "falsifiable", "辩证法": "dialectic",
    "形而上学": "metaphysics", "悖论": "paradox", "矛盾": "contradiction",
    "假设": "hypothesis", "证明": "proof", "推导": "derivation",
    "演算": "calculus", "决策理论": "decision_theory", "博弈论": "game_theory",
    "纳什均衡": "nash", "夏普利值": "shapley", "ahp": "ahp",
    "层次分析": "ahp", "熵权": "entropy", "信息熵": "info_entropy",
    "心智模型": "mental_model", "认知": "cognition", "认知偏差": "cog_bias",
    "确认偏误": "confirmation_bias", "幸存者偏差": "survivor_bias",
    "锚定效应": "anchoring", "框架效应": "framing",
    "可用性启发": "avail_heuristic", "代表性启发": "representative",
    "损失厌恶": "loss_aversion", "禀赋效应": "endowment", "框架": "framework",
    "五看三定": "5look3set", "鱼骨图": "fishbone", "5w": "5w",
    "5why": "5why", "6sigma": "6sigma", "pdca": "pdca", "okr": "okr",
    "kpi": "kpi", "smart": "smart", "swot": "swot", "pest": "pest",
    "4p": "4p", "4c": "4c", "stp": "stp", "bcg": "bcg", "ansoff": "ansoff",
    "波特五力": "porter5", "价值链": "value_chain", "商业模式": "business_model",
    "画布": "canvas", "精益": "lean", "敏捷": "agile", "scrum": "scrum",
    "kanban": "kanban", "看板": "kanban", "瀑布": "waterfall",
    "迭代": "iteration", "增量": "increment", "mvp": "mvp", "pmf": "pmf",
    "gtm": "gtm", "sop": "sop", "sla": "sla", "slo": "slo", "oli": "oli",
    "联想": "lenovo", "联想集团": "lenovo", "华为": "huawei",
    "阿里": "alibaba", "阿里巴巴": "alibaba", "腾讯": "tencent",
    "字节": "bytedance", "字节跳动": "bytedance", "百度": "baidu",
    "meta": "meta", "谷歌": "google", "google": "google",
    "微软": "microsoft", "microsoft": "microsoft", "亚马逊": "amazon",
    "amazon": "amazon", "aws": "aws", "azure": "azure", "阿里云": "aliyun",
    "腾讯云": "tencent_cloud", "华为云": "huawei_cloud", "百度云": "baidu_cloud",
    "火山引擎": "volc", "飞书": "feishu", "钉钉": "dingtalk", "企微": "wecom",
    "微信": "wechat", "小红书": "xhs", "抖音": "douyin", "tiktok": "tiktok",
    "视频号": "wechat_channel", "公众号": "mp", "微博": "weibo", "知乎": "zhihu",
    "b站": "bilibili", "bilibili": "bilibili", "英伟达": "nvidia",
    "nvidia": "nvidia", "英特尔": "intel", "intel": "intel", "amd": "amd",
    "超威": "amd", "arm": "arm", "高通": "qualcomm", "qualcomm": "qualcomm",
    "博通": "broadcom", "broadcom": "broadcom", "海光": "hygon",
    "寒武纪": "cambricon", "燧原": "enycore", "燧原科技": "enycore",
    "壁仞": "biren", "壁仞科技": "biren", "摩尔线程": "mthreads",
    "天数智芯": "iluvatar", "沐曦": "metax", "芯擎": "siengine",
    "江原科技": "jiangyuan", "江原": "jiangyuan", "紫光": "unis",
    "紫光股份": "unis", "浪潮": "inspur", "inspur": "inspur",
    "中科曙光": "sugon", "曙光": "sugon", "sugon": "sugon",
    "戴尔": "dell", "dell": "dell", "惠普": "hpe", "hpe": "hpe",
    "hpi": "hpi", "思科": "cisco", "cisco": "cisco", "新华三": "h3c",
    "h3c": "h3c", "锐捷": "ruijie", "ruijie": "ruijie", "迈普": "maipu",
    "深信服": "sangfor", "sangfor": "sangfor", "奇安信": "qianxin",
    "qianxin": "qianxin", "绿盟": "nsfocus", "nsfocus": "nsfocus",
    "启明": "venustech", "venustech": "venustech", "天融信": "topsec",
    "topsec": "topsec", "安恒": "dbappsecurity", "dbappsecurity": "dbappsecurity",
    "山石": "hillstone", "hillstone": "hillstone", "网神": "netsensor",
    "网御": "leadsec", "绿盟科技": "nsfocus", "云从": "cloudwalk",
    "云从科技": "cloudwalk", "商汤": "sensetime", "商汤科技": "sensetime",
    "旷视": "megvii", "旷视科技": "megvii", "依图": "yitu",
    "依图科技": "yitu", "云知声": "unisound", "云知声科技": "unisound",
    "思必驰": "aispeech", "出门问问": "mobvoi", "地平线": "horizon",
    "地平线机器人": "horizon", "黑芝麻": "blacksesame", "黑芝麻智能": "blacksesame",
    "后摩智能": "houmo", "后摩": "houmo", "芯驰": "semidrive",
    "芯驰科技": "semidrive", "杰发": "autochips", "杰发科技": "autochips",
    "全志": "allwinner", "全志科技": "allwinner", "瑞芯微": "rockchip",
    "瑞芯微电子": "rockchip", "晶晨": "amlogic", "晶晨半导体": "amlogic",
    "兆易": "giga", "兆易创新": "giga", "北京君正": "ingenic", "君正": "ingenic",
    "紫光展锐": "unisoc", "展锐": "unisoc", "unisoc": "unisoc",
    "自动驾驶": "autonomous", "智能驾驶": "autonomous", "车载": "vehicle",
    "汽车": "auto", "driveos": "driveos", "低空": "low_altitude",
    "无人机": "drone", "机器人": "robot", "具身智能": "embodied",
    "人形机器人": "humanoid", "工业": "industrial", "工业互联网": "iiot",
    "制造": "manufacturing", "智能制造": "smart_mfg", "医疗": "medical",
    "医疗健康": "healthcare", "金融": "finance", "金融科技": "fintech",
    "教育": "education", "在线教育": "online_edu", "零售": "retail",
    "电商": "ecommerce", "物流": "logistics", "能源": "energy",
    "电力": "power", "电网": "grid", "政务": "gov", "智慧城市": "smart_city",
    "智慧交通": "smart_transit", "智慧医疗": "smart_health",
    "智慧教育": "smart_edu", "智慧能源": "smart_energy",
    "智慧农业": "smart_agri", "农业": "agriculture",
    "智能制造": "smart_mfg", "游戏": "game", "娱乐": "entertainment",
    "媒体": "media", "广告": "ad", "营销": "marketing", "销售": "sales",
    "客服": "cs", "客户服务": "cs", "运营": "ops", "产品": "product",
    "pm": "pm", "产品经理": "pm", "ux": "ux", "ui": "ui",
    "用户": "user", "用户体验": "ux", "设计": "design", "内容": "content",
    "运营": "ops", "商业化": "commercialization",
    "iso27001": "iso27001", "iso14001": "iso14001", "iso45001": "iso45001",
    "iso9001": "iso9001", "iso26262": "iso26262", "iso21434": "iso21434",
    "aspice": "aspice", "iso": "iso", "cmmi": "cmmi", "itil": "itil",
    "cobit": "cobit", "togaf": "togaf", "通用数据保护": "gdpr",
    "gdpr": "gdpr", "ai法案": "ai_act", "ai act": "ai_act",
    "ai安全": "ai_security", "safety": "safety", "security": "security",
    "security by design": "sec_by_design", "零信任": "zero_trust",
    "纵深防御": "defense_in_depth", "最小权限": "least_priv",
    "最小化": "minimize",
    "概念": "concept", "定义": "definition", "原理": "principle",
    "本质": "essence", "核心": "core", "关键": "key", "基础": "basic",
    "基础工具": "basic_tool", "底层": "underlying", "底层逻辑": "underlying_logic",
    "结构": "structure", "层次": "hierarchy", "层级": "level",
    "级别": "level", "阶段": "stage", "周期": "cycle", "生命周期": "lifecycle",
    "环节": "stage", "步骤": "step", "流程": "process", "工作流": "workflow",
    "自动化": "automation", "工程": "engineering", "项目": "project",
    "项目管理": "pm", "进度": "progress", "里程碑": "milestone",
    "风险": "risk", "挑战": "challenge", "难点": "difficulty",
    "痛点": "pain_point", "需求": "requirement", "需求分析": "req_analysis",
    "可行性": "feasibility", "可行": "feasible", "评估": "evaluation",
    "评价": "evaluate", "审视": "review", "审查": "review",
    "审计": "audit", "改进": "improve", "改进措施": "improvement",
    "迭代": "iterate", "优化": "optimize", "升级": "upgrade",
    "重构": "refactor", "重写": "rewrite", "重整": "reorganize",
    "整理": "organize", "组织": "organize", "归类": "classify",
    "分类": "classify", "分组": "group", "聚合": "aggregate",
    "分解": "decompose", "拆解": "decompose", "拆分": "split",
    "合并": "merge", "整合": "integrate", "融合": "fuse",
    "云智融合": "cloud_ai_fuse", "中台": "mid_platform",
    "业务中台": "biz_mid", "数据中台": "data_mid", "ai中台": "ai_mid",
    "技术中台": "tech_mid", "前台": "frontend", "后台": "backend",
    "后端": "backend", "前端": "frontend", "全栈": "fullstack",
    "ai全栈": "ai_fullstack", "渠道": "channel", "生态": "ecosystem",
    "生态系统": "ecosystem", "生态体系": "ecosystem", "伙伴": "partner",
    "合作伙伴": "partner", "联盟": "alliance", "标准": "standard",
    "标准化": "standardize", "规范化": "normalize", "流程化": "process_oriented",
    "工具化": "tool_oriented", "数字化": "digital",
    "数字化转型": "digital_trans", "智能化": "intelligent",
    "数智化": "dig_intelligent", "上云": "cloud_migration",
    "私有化": "privatize", "国产化": "localization", "信创": "xinchuang",
    "自主可控": "autonomous_ctrl",
    "质量": "quality", "效率": "efficiency", "效能": "effectiveness",
    "价值": "value", "成本效益": "cost_effect", "效益": "benefit",
    "收益": "benefit", "效果": "effect", "结果": "result",
    "目标": "goal", "目的": "purpose", "意义": "meaning", "影响": "impact",
    "作用": "effect", "用途": "usage", "用法": "usage", "应用": "apply",
    "实战": "practice", "实操": "hands_on", "操作": "operation",
    "指引": "guide", "指南": "guide", "教程": "tutorial", "手册": "manual",
    "清单": "checklist", "checklist": "checklist", "模板": "template",
    "范例": "example", "样例": "sample", "示例": "example", "demo": "demo",
    "poc": "poc", "试点": "pilot", "落地": "landing", "实施": "implement",
    "推广": "promote", "复制": "replicate", "复用": "reuse", "通用": "general",
    "复用性": "reusability", "可移植": "portable", "可扩展": "scalable",
    "可配置": "configurable", "可定制": "customizable", "可观测": "observable",
    "可监控": "monitorable", "可维护": "maintainable", "可管理": "manageable",
    "可控": "controllable", "可控性": "controllability", "可控度": "control_level",
    "可控范围": "control_scope",
    "推荐": "recommend", "列举": "list", "举例": "example", "示例": "example",
    "讲解": "explain", "讲一下": "explain", "解释": "explain",
    "理解": "understand", "深入": "deep", "深度": "depth",
    "全面": "comprehensive", "完整": "complete", "整体": "overall",
    "总体": "overall", "全局": "global", "局部": "local", "细节": "detail",
    "概述": "overview", "简介": "intro", "导论": "intro", "入门": "intro",
    "进阶": "advanced", "高级": "advanced", "基础": "basic",
    "底层": "underlying", "原理": "principle", "本质": "essence",
    "机制": "mechanism", "机理": "mechanism", "规律": "law",
    "规则": "rule", "约束": "constraint", "限制": "limit", "边界": "boundary",
    "范围": "scope", "领域": "domain", "范畴": "category", "主题": "topic",
    "话题": "topic", "焦点": "focus", "重点": "focus", "核心": "core",
    "关键": "key", "要素": "factor", "因素": "factor", "条件": "condition",
    "前提": "premise", "假设": "hypothesis", "推测": "speculate",
    "推断": "infer", "推论": "inference", "演绎": "deduce",
    "归纳": "induce", "总结": "summarize", "概括": "generalize",
    "提炼": "extract", "提纲": "outline", "大纲": "outline",
    "框架": "framework", "脉络": "context", "逻辑链": "logic_chain",
    "思路": "approach", "思考": "thinking", "反思": "reflect",
    "审视": "examine", "评估": "evaluate", "衡量": "measure",
    "测量": "measure", "度量": "metric", "指标": "metric",
    "基准": "baseline", "基线": "baseline", "标准": "standard",
    "标杆": "benchmark", "对标": "benchmark", "对标情况": "benchmark",
    "竞品": "competitor", "竞争": "competition", "竞争对手": "competitor",
    "生态竞争": "eco_competition", "格局": "landscape", "全景": "panorama",
    "全貌": "panorama", "图谱": "atlas", "地图": "map",
    "路线图": "roadmap", "时间表": "timeline", "节奏": "pace",
    "速度": "speed", "周期": "cycle", "阶段": "phase", "节点": "node",
    "检查点": "checkpoint", "转折点": "turning", "临界点": "critical",
    "奇点": "singularity",
}


def lookup(term):
    if not term:
        return None
    term = term.strip()
    if term in TERM_DICT:
        return TERM_DICT[term]
    low = term.lower()
    if low in TERM_DICT:
        return TERM_DICT[low]
    return None
